const STATUS_SENDING = "SENDING";
const STATUS_APPROVED = "APPROVED";
const STATUS_REJECTED = "REJECTED";
const STATUS_NEW = "NEW";

export { STATUS_SENDING, STATUS_APPROVED, STATUS_REJECTED, STATUS_NEW };
