const HTTP_OK_STATUS = 200;
const HTTP_CREATED_STATUS = 201;
const HTTP_UNAUTHORIZED = 401;
const HTTP_ERROR = 400;
const HTTP_NOT_FOUND = 404;

module.exports = {
  HTTP_OK_STATUS,
  HTTP_CREATED_STATUS,
  HTTP_UNAUTHORIZED,
  HTTP_ERROR,
  HTTP_NOT_FOUND,
};
